<?php declare(strict_types = 1);

/**
 * RoutingKey.php
 *
 * @license        More in LICENSE.md
 * @copyright      https://www.fastybird.com
 * @author         Adam Kadlec <adam.kadlec@fastybird.com>
 * @package        FastyBird:MetadataLibrary!
 * @subpackage     Types
 * @since          1.0.0
 *
 * @date           05.10.21
 */

namespace FastyBird\Library\Metadata\Types;

use Consistence;
use FastyBird\Library\Metadata;
use function strval;

/**
 * Routing keys types
 *
 * @package        FastyBird:MetadataLibrary!
 * @subpackage     Types
 *
 * @author         Adam Kadlec <adam.kadlec@fastybird.com>
 */
class RoutingKey extends Consistence\Enum\Enum
{

	/**
	 * Define types
	 */
	public const CONNECTOR_CONTROL_ACTION = Metadata\Constants::MESSAGE_BUS_CONNECTOR_CONTROL_ACTION_ROUTING_KEY;

	public const CONNECTOR_PROPERTY_ACTION = Metadata\Constants::MESSAGE_BUS_CONNECTOR_PROPERTY_ACTION_ROUTING_KEY;

	public const DEVICE_CONTROL_ACTION = Metadata\Constants::MESSAGE_BUS_DEVICE_CONTROL_ACTION_ROUTING_KEY;

	public const DEVICE_PROPERTY_ACTION = Metadata\Constants::MESSAGE_BUS_DEVICE_PROPERTY_ACTION_ROUTING_KEY;

	public const CHANNEL_CONTROL_ACTION = Metadata\Constants::MESSAGE_BUS_CHANNEL_CONTROL_ACTION_ROUTING_KEY;

	public const CHANNEL_PROPERTY_ACTION = Metadata\Constants::MESSAGE_BUS_CHANNEL_PROPERTY_ACTION_ROUTING_KEY;

	public const TRIGGER_CONTROL_ACTION = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONTROL_ACTION_ROUTING_KEY;

	public const MODULE_MESSAGE = Metadata\Constants::MESSAGE_BUS_MODULE_MESSAGE_ROUTING_KEY;

	public const PLUGIN_MESSAGE = Metadata\Constants::MESSAGE_BUS_PLUGIN_MESSAGE_ROUTING_KEY;

	public const CONNECTOR_MESSAGE = Metadata\Constants::MESSAGE_BUS_CONNECTOR_MESSAGE_ROUTING_KEY;

	public const TRIGGER_MESSAGE = Metadata\Constants::MESSAGE_BUS_TRIGGER_MESSAGE_ROUTING_KEY;

	public const ACCOUNT_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_ACCOUNT_DOCUMENT_REPORTED_ROUTING_KEY;

	public const ACCOUNT_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_ACCOUNT_DOCUMENT_CREATED_ROUTING_KEY;

	public const ACCOUNT_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_ACCOUNT_DOCUMENT_UPDATED_ROUTING_KEY;

	public const ACCOUNT_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_ACCOUNT_DOCUMENT_DELETED_ROUTING_KEY;

	public const EMAIL_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_EMAIL_DOCUMENT_REPORTED_ROUTING_KEY;

	public const EMAIL_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_EMAIL_DOCUMENT_CREATED_ROUTING_KEY;

	public const EMAIL_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_EMAIL_DOCUMENT_UPDATED_ROUTING_KEY;

	public const EMAIL_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_EMAIL_DOCUMENT_DELETED_ROUTING_KEY;

	public const IDENTITY_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_IDENTITY_DOCUMENT_REPORTED_ROUTING_KEY;

	public const IDENTITY_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_IDENTITY_DOCUMENT_CREATED_ROUTING_KEY;

	public const IDENTITY_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_IDENTITY_DOCUMENT_UPDATED_ROUTING_KEY;

	public const IDENTITY_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_IDENTITY_DOCUMENT_DELETED_ROUTING_KEY;

	public const ROLE_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_ROLE_DOCUMENT_REPORTED_ROUTING_KEY;

	public const ROLE_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_ROLE_DOCUMENT_CREATED_ROUTING_KEY;

	public const ROLE_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_ROLE_DOCUMENT_UPDATED_ROUTING_KEY;

	public const ROLE_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_ROLE_DOCUMENT_DELETED_ROUTING_KEY;

	public const DEVICE_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_DEVICE_DOCUMENT_REPORTED_ROUTING_KEY;

	public const DEVICE_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_DEVICE_DOCUMENT_CREATED_ROUTING_KEY;

	public const DEVICE_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_DEVICE_DOCUMENT_UPDATED_ROUTING_KEY;

	public const DEVICE_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_DEVICE_DOCUMENT_DELETED_ROUTING_KEY;

	public const DEVICE_PROPERTY_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_DEVICE_PROPERTY_DOCUMENT_REPORTED_ROUTING_KEY;

	public const DEVICE_PROPERTY_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_DEVICE_PROPERTY_DOCUMENT_CREATED_ROUTING_KEY;

	public const DEVICE_PROPERTY_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_DEVICE_PROPERTY_DOCUMENT_UPDATED_ROUTING_KEY;

	public const DEVICE_PROPERTY_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_DEVICE_PROPERTY_DOCUMENT_DELETED_ROUTING_KEY;

	public const DEVICE_CONTROL_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_DEVICE_CONTROL_DOCUMENT_REPORTED_ROUTING_KEY;

	public const DEVICE_CONTROL_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_DEVICE_CONTROL_DOCUMENT_CREATED_ROUTING_KEY;

	public const DEVICE_CONTROL_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_DEVICE_CONTROL_DOCUMENT_UPDATED_ROUTING_KEY;

	public const DEVICE_CONTROL_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_DEVICE_CONTROL_DOCUMENT_DELETED_ROUTING_KEY;

	public const CHANNEL_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_CHANNEL_DOCUMENT_REPORTED_ROUTING_KEY;

	public const CHANNEL_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_CHANNEL_DOCUMENT_CREATED_ROUTING_KEY;

	public const CHANNEL_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_CHANNEL_DOCUMENT_UPDATED_ROUTING_KEY;

	public const CHANNEL_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_CHANNEL_DOCUMENT_DELETED_ROUTING_KEY;

	public const CHANNEL_PROPERTY_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_CHANNEL_PROPERTY_DOCUMENT_REPORTED_ROUTING_KEY;

	public const CHANNEL_PROPERTY_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_CHANNEL_PROPERTY_DOCUMENT_CREATED_ROUTING_KEY;

	public const CHANNEL_PROPERTY_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_CHANNEL_PROPERTY_DOCUMENT_UPDATED_ROUTING_KEY;

	public const CHANNEL_PROPERTY_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_CHANNEL_PROPERTY_DOCUMENT_DELETED_ROUTING_KEY;

	public const CHANNEL_CONTROL_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_CHANNEL_CONTROL_DOCUMENT_REPORTED_ROUTING_KEY;

	public const CHANNEL_CONTROL_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_CHANNEL_CONTROL_DOCUMENT_CREATED_ROUTING_KEY;

	public const CHANNEL_CONTROL_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_CHANNEL_CONTROL_DOCUMENT_UPDATED_ROUTING_KEY;

	public const CHANNEL_CONTROL_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_CHANNEL_CONTROL_DOCUMENT_DELETED_ROUTING_KEY;

	public const CONNECTOR_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_DOCUMENT_REPORTED_ROUTING_KEY;

	public const CONNECTOR_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_DOCUMENT_CREATED_ROUTING_KEY;

	public const CONNECTOR_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_DOCUMENT_UPDATED_ROUTING_KEY;

	public const CONNECTOR_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_DOCUMENT_DELETED_ROUTING_KEY;

	public const CONNECTOR_PROPERTY_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_PROPERTY_DOCUMENT_REPORTED_ROUTING_KEY;

	public const CONNECTOR_PROPERTY_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_PROPERTY_DOCUMENT_CREATED_ROUTING_KEY;

	public const CONNECTOR_PROPERTY_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_PROPERTY_DOCUMENT_UPDATED_ROUTING_KEY;

	public const CONNECTOR_PROPERTY_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_PROPERTY_DOCUMENT_DELETED_ROUTING_KEY;

	public const CONNECTOR_CONTROL_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_CONTROL_DOCUMENT_REPORTED_ROUTING_KEY;

	public const CONNECTOR_CONTROL_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_CONTROL_DOCUMENT_CREATED_ROUTING_KEY;

	public const CONNECTOR_CONTROL_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_CONTROL_DOCUMENT_UPDATED_ROUTING_KEY;

	public const CONNECTOR_CONTROL_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_CONTROL_DOCUMENT_DELETED_ROUTING_KEY;

	public const TRIGGER_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_TRIGGER_DOCUMENT_REPORTED_ROUTING_KEY;

	public const TRIGGER_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_DOCUMENT_CREATED_ROUTING_KEY;

	public const TRIGGER_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_DOCUMENT_UPDATED_ROUTING_KEY;

	public const TRIGGER_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_TRIGGER_DOCUMENT_DELETED_ROUTING_KEY;

	public const TRIGGER_CONTROL_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONTROL_DOCUMENT_REPORTED_ROUTING_KEY;

	public const TRIGGER_CONTROL_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONTROL_DOCUMENT_CREATED_ROUTING_KEY;

	public const TRIGGER_CONTROL_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONTROL_DOCUMENT_UPDATED_ROUTING_KEY;

	public const TRIGGER_CONTROL_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONTROL_DOCUMENT_DELETED_ROUTING_KEY;

	public const TRIGGER_ACTION_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_TRIGGER_ACTION_DOCUMENT_REPORTED_ROUTING_KEY;

	public const TRIGGER_ACTION_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_ACTION_DOCUMENT_CREATED_ROUTING_KEY;

	public const TRIGGER_ACTION_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_ACTION_DOCUMENT_UPDATED_ROUTING_KEY;

	public const TRIGGER_ACTION_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_TRIGGER_ACTION_DOCUMENT_DELETED_ROUTING_KEY;

	public const TRIGGER_NOTIFICATION_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_TRIGGER_NOTIFICATION_DOCUMENT_REPORTED_ROUTING_KEY;

	public const TRIGGER_NOTIFICATION_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_NOTIFICATION_DOCUMENT_CREATED_ROUTING_KEY;

	public const TRIGGER_NOTIFICATION_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_NOTIFICATION_DOCUMENT_UPDATED_ROUTING_KEY;

	public const TRIGGER_NOTIFICATION_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_TRIGGER_NOTIFICATION_DOCUMENT_DELETED_ROUTING_KEY;

	public const TRIGGER_CONDITION_DOCUMENT_REPORTED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONDITION_DOCUMENT_REPORTED_ROUTING_KEY;

	public const TRIGGER_CONDITION_DOCUMENT_CREATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONDITION_DOCUMENT_CREATED_ROUTING_KEY;

	public const TRIGGER_CONDITION_DOCUMENT_UPDATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONDITION_DOCUMENT_UPDATED_ROUTING_KEY;

	public const TRIGGER_CONDITION_DOCUMENT_DELETED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONDITION_DOCUMENT_DELETED_ROUTING_KEY;

	public function __toString(): string
	{
		return strval(self::getValue());
	}

}
