<?php declare(strict_types = 1);

/**
 * RoutingKey.php
 *
 * @license        More in LICENSE.md
 * @copyright      https://www.fastybird.com
 * @author         Adam Kadlec <adam.kadlec@fastybird.com>
 * @package        FastyBird:Metadata!
 * @subpackage     Types
 * @since          0.7.4
 *
 * @date           05.10.21
 */

namespace FastyBird\Library\Metadata\Types;

use Consistence;
use FastyBird\Library\Metadata;
use function strval;

/**
 * Routing keys types
 *
 * @package        FastyBird:Metadata!
 * @subpackage     Types
 *
 * @author         Adam Kadlec <adam.kadlec@fastybird.com>
 */
class RoutingKey extends Consistence\Enum\Enum
{

	/**
	 * Define types
	 */
	public const ROUTE_CONNECTOR_CONTROL_ACTION = Metadata\Constants::MESSAGE_BUS_CONNECTOR_CONTROL_ACTION_ROUTING_KEY;

	public const ROUTE_CONNECTOR_PROPERTY_ACTION = Metadata\Constants::MESSAGE_BUS_CONNECTOR_PROPERTY_ACTION_ROUTING_KEY;

	public const ROUTE_DEVICE_CONTROL_ACTION = Metadata\Constants::MESSAGE_BUS_DEVICE_CONTROL_ACTION_ROUTING_KEY;

	public const ROUTE_DEVICE_PROPERTY_ACTION = Metadata\Constants::MESSAGE_BUS_DEVICE_PROPERTY_ACTION_ROUTING_KEY;

	public const ROUTE_CHANNEL_CONTROL_ACTION = Metadata\Constants::MESSAGE_BUS_CHANNEL_CONTROL_ACTION_ROUTING_KEY;

	public const ROUTE_CHANNEL_PROPERTY_ACTION = Metadata\Constants::MESSAGE_BUS_CHANNEL_PROPERTY_ACTION_ROUTING_KEY;

	public const ROUTE_TRIGGER_CONTROL_ACTION = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONTROL_ACTION_ROUTING_KEY;

	public const ROUTE_MODULE_MESSAGE = Metadata\Constants::MESSAGE_BUS_MODULE_MESSAGE_ROUTING_KEY;

	public const ROUTE_PLUGIN_MESSAGE = Metadata\Constants::MESSAGE_BUS_PLUGIN_MESSAGE_ROUTING_KEY;

	public const ROUTE_CONNECTOR_MESSAGE = Metadata\Constants::MESSAGE_BUS_CONNECTOR_MESSAGE_ROUTING_KEY;

	public const ROUTE_TRIGGER_MESSAGE = Metadata\Constants::MESSAGE_BUS_TRIGGER_MESSAGE_ROUTING_KEY;

	public const ROUTE_ACCOUNT_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_ACCOUNT_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_ACCOUNT_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_ACCOUNT_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_ACCOUNT_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_ACCOUNT_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_ACCOUNT_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_ACCOUNT_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_EMAIL_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_EMAIL_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_EMAIL_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_EMAIL_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_EMAIL_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_EMAIL_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_EMAIL_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_EMAIL_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_IDENTITY_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_IDENTITY_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_IDENTITY_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_IDENTITY_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_IDENTITY_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_IDENTITY_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_IDENTITY_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_IDENTITY_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_ROLE_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_ROLE_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_ROLE_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_ROLE_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_ROLE_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_ROLE_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_ROLE_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_ROLE_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_DEVICE_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_DEVICE_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_DEVICE_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_DEVICE_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_DEVICE_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_DEVICE_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_DEVICE_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_DEVICE_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_DEVICE_PROPERTY_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_DEVICE_PROPERTY_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_DEVICE_PROPERTY_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_DEVICE_PROPERTY_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_DEVICE_PROPERTY_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_DEVICE_PROPERTY_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_DEVICE_PROPERTY_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_DEVICE_PROPERTY_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_DEVICE_CONTROL_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_DEVICE_CONTROL_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_DEVICE_CONTROL_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_DEVICE_CONTROL_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_DEVICE_CONTROL_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_DEVICE_CONTROL_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_DEVICE_CONTROL_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_DEVICE_CONTROL_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_DEVICE_ATTRIBUTE_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_DEVICE_ATTRIBUTE_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_DEVICE_ATTRIBUTE_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_DEVICE_ATTRIBUTE_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_DEVICE_ATTRIBUTE_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_DEVICE_ATTRIBUTE_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_DEVICE_ATTRIBUTE_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_DEVICE_ATTRIBUTE_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_CHANNEL_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_CHANNEL_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_CHANNEL_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_CHANNEL_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_CHANNEL_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_CHANNEL_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_CHANNEL_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_CHANNEL_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_CHANNEL_PROPERTY_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_CHANNEL_PROPERTY_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_CHANNEL_PROPERTY_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_CHANNEL_PROPERTY_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_CHANNEL_PROPERTY_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_CHANNEL_PROPERTY_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_CHANNEL_PROPERTY_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_CHANNEL_PROPERTY_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_CHANNEL_CONTROL_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_CHANNEL_CONTROL_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_CHANNEL_CONTROL_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_CHANNEL_CONTROL_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_CHANNEL_CONTROL_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_CHANNEL_CONTROL_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_CHANNEL_CONTROL_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_CHANNEL_CONTROL_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_CONNECTOR_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_CONNECTOR_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_CONNECTOR_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_CONNECTOR_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_CONNECTOR_PROPERTY_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_PROPERTY_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_CONNECTOR_PROPERTY_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_PROPERTY_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_CONNECTOR_PROPERTY_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_PROPERTY_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_CONNECTOR_PROPERTY_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_PROPERTY_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_CONNECTOR_CONTROL_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_CONTROL_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_CONNECTOR_CONTROL_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_CONTROL_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_CONNECTOR_CONTROL_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_CONTROL_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_CONNECTOR_CONTROL_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_CONNECTOR_CONTROL_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_TRIGGER_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_TRIGGER_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_TRIGGER_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_TRIGGER_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_TRIGGER_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_TRIGGER_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_TRIGGER_CONTROL_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONTROL_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_TRIGGER_CONTROL_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONTROL_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_TRIGGER_CONTROL_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONTROL_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_TRIGGER_CONTROL_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONTROL_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_TRIGGER_ACTION_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_TRIGGER_ACTION_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_TRIGGER_ACTION_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_ACTION_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_TRIGGER_ACTION_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_ACTION_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_TRIGGER_ACTION_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_TRIGGER_ACTION_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_TRIGGER_NOTIFICATION_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_TRIGGER_NOTIFICATION_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_TRIGGER_NOTIFICATION_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_NOTIFICATION_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_TRIGGER_NOTIFICATION_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_NOTIFICATION_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_TRIGGER_NOTIFICATION_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_TRIGGER_NOTIFICATION_ENTITY_DELETED_ROUTING_KEY;

	public const ROUTE_TRIGGER_CONDITION_ENTITY_REPORTED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONDITION_ENTITY_REPORTED_ROUTING_KEY;

	public const ROUTE_TRIGGER_CONDITION_ENTITY_CREATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONDITION_ENTITY_CREATED_ROUTING_KEY;

	public const ROUTE_TRIGGER_CONDITION_ENTITY_UPDATED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONDITION_ENTITY_UPDATED_ROUTING_KEY;

	public const ROUTE_TRIGGER_CONDITION_ENTITY_DELETED = Metadata\Constants::MESSAGE_BUS_TRIGGER_CONDITION_ENTITY_DELETED_ROUTING_KEY;

	public function __toString(): string
	{
		return strval(self::getValue());
	}

}
